var relatedTitles=[],relatedTitlesNum=0,relatedUrls=[];function bacajuga(a){for(var c=0;c<a.feed.entry.length;c++){var d=a.feed.entry[c];relatedTitles[relatedTitlesNum]=d.title.$t;for(var b=0;b<d.link.length;b++)if("alternate"==d.link[b].rel){relatedUrls[relatedTitlesNum]=d.link[b].href;relatedTitlesNum++;break}}}
function removeRelatedDuplicates(){for(var a=[],c=[],d=0;d<relatedUrls.length;d++)contains(a,relatedUrls[d])||(a.length+=1,a[a.length-1]=relatedUrls[d],c.length+=1,c[c.length-1]=relatedTitles[d]);relatedTitles=c;relatedUrls=a}function contains(a,c){for(var d=0;d<a.length;d++)if(a[d]==c)return!0;return!1}
function printRelatedLabels(a){for(var c=0;c<relatedUrls.length;c++)relatedUrls[c]==a&&(relatedUrls.splice(c,1),relatedTitles.splice(c,1));a=Math.floor((relatedTitles.length-1)*Math.random());c=0;if(1==widgetBacaJuga&&1<relatedTitles.length){for(document.write("<div class='baca-juga-wrap'>"+judulbacajuga+"<ul>");c<relatedTitles.length&&20>c&&c<jumlahbacajuga;)document.write('<li><a href="'+relatedUrls[a]+'">'+relatedTitles[a]+"</a></li>"),a<relatedTitles.length-1?a++:a=0,c++;document.write("</ul></div>")}relatedUrls.splice(0,
relatedUrls.length);relatedTitles.splice(0,relatedTitles.length)};if(1==relatedPosts){var randomRelatedIndex,showRelatedPost;!function(a,c,d){var b={widgetTitle:"<h4>Artikel Terkait:</h4>",widgetStyle:3,homePage:"http://www.dte.web.id",numPosts:8,summaryLength:0,titleLength:"auto",thumbnailWidth:255,thumbnailHeight:170,noImage:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAA3NCSVQICAjb4U/gAAAADElEQVQImWOor68HAAL+AX7vOF2TAAAAAElFTkSuQmCC",containerId:"related-post",newTabLink:!1,moreText:"Baca Selengkapnya",callBack:function(){}},f;for(f in relatedPostConfig)b[f]=
"undefined"==relatedPostConfig[f]?b[f]:relatedPostConfig[f];var g=function(b){var a=c.createElement("script");a.type="text/javascript";a.src=b;d.appendChild(a)},l=function(b){var a=b.length;if(0===a)return!1;for(;--a;){var c=Math.floor(Math.random()*(a+1));var d=b[a];b[a]=b[c];b[c]=d}return b},h="object"==typeof labelArray&&0<labelArray.length?"/-/"+l(labelArray)[0]:"";randomRelatedIndex=function(a){var c;a=a.feed.openSearch$totalResults.$t-b.numPosts;a=(c=0<a?a:1,Math.floor(Math.random()*(c-1+1))+
1);g(b.homePage.replace(/\/$/,"")+"/feeds/posts/summary"+h+"?alt=json-in-script&orderby=updated&start-index="+a+"&max-results="+b.numPosts+"&callback=showRelatedPost")};showRelatedPost=function(a){var c=document.getElementById(b.containerId),d=l(a.feed.entry),f=b.widgetStyle,g=b.widgetTitle+'<ul class="related-post-style-'+f+'">',h=b.newTabLink?' target="_blank"':"";if(c){for(var e=0;e<b.numPosts&&e!=d.length;e++){a=d[e].title.$t;var n="auto"!==b.titleLength&&b.titleLength<a.length?a.substring(0,
b.titleLength)+"&hellip;":a;var p="media$thumbnail"in d[e]&&!1!==b.thumbnailWidth?d[e].media$thumbnail.url.replace(/.*?:\/\//g,"//").replace(/\/s[0-9]+(\-c)?/,"/w"+b.thumbnailWidth+"-h"+b.thumbnailHeight+"-c"):b.noImage;"summary"in d[e]&&0<b.summaryLength&&d[e].summary.$t.replace(/<br ?\/?>/g," ").replace(/<.*?>/g,"").replace(/[<>]/g,"").substring(0,b.summaryLength);for(var k=0,q=d[e].link.length;k<q;k++)var m="alternate"==d[e].link[k].rel?d[e].link[k].href:"#";3==f&&(g+='<li class="related-post-item" tabindex="0"><a class="related-post-item-title" href="'+
m+'"'+h+'><img alt="" class="lazyload related-post-item-thumbnail" data-src="'+p+'" width="'+b.thumbnailWidth+'" height="'+b.thumbnailHeight+'"></a><div class="related-post-item-tooltip"><a class="related-post-item-title" title="'+a+'" href="'+m+'"'+h+">"+n+'</a></div><span style="display:block;clear:both;"></span></li>')}c.innerHTML=g+'</ul><span style="display:block;clear:both;"></span>';b.callBack()}};g(b.homePage.replace(/\/$/,"")+"/feeds/posts/summary"+h+"?alt=json-in-script&orderby=updated&max-results=0&callback=randomRelatedIndex")}(window,
document,document.getElementsByTagName("head")[0])};
